// SPDX-FileCopyrightText: 2021 tippfehlr <tippfehlr@tippfehlr.dev>
// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
	T extends ColumnType<infer S, infer I, infer U>
		? ColumnType<S, I | undefined, U>
		: ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ActiveTemporaryRoles {
	guildID: string;
	roleID: string;
	userID: string;
}

export interface ActiveTemporaryRolesHashed {
	guildID: string;
	roleID: string;
	userIDHash: string;
}

export interface ActivityRoles {
	activityName: string;
	details: string;
	exact: Generated<boolean>;
	guildID: string;
	permanent: Generated<boolean>;
	removeAfterDays: number | null;
	roleID: string;
	state: string;
}

export interface ActivityStats {
	activityName: string;
	count: Generated<number>;
	guildID: string;
}

export interface Guilds {
	approxMemberCount: number | null;
	approxMemberCountLastUpdate: Timestamp | null;
	guildID: string;
	lastCheckRoles: Timestamp | null;
	requiredRoleID: string | null;
}

export interface ScheduledRoleActions {
	action: string;
	guildID: string;
	roleID: string;
	scheduledDate: Timestamp;
	userID: string;
}

export interface StatusRoles {
	guildID: string;
	roleID: string;
	type: number;
}

export interface Users {
	autorole: Generated<boolean>;
	userID: string;
}

export interface UsersHashed {
	autorole: Generated<boolean>;
	userIDHash: string;
}

export interface DB {
	activeTemporaryRoles: ActiveTemporaryRoles;
	activeTemporaryRolesHashed: ActiveTemporaryRolesHashed;
	activityRoles: ActivityRoles;
	activityStats: ActivityStats;
	guilds: Guilds;
	scheduledRoleActions: ScheduledRoleActions;
	statusRoles: StatusRoles;
	users: Users;
	usersHashed: UsersHashed;
}
